export const GET_STUDENT_DATA = "GET_STUDENT_DATA";
export const CHANGE_NAME = "CHANGE_NAME";
export const CHANGE_OBJECTIVE = "CHANGE_OBJECTIVE";
export const CHANGE_CONTACT_INFORMATION = "CHANGE_CONTACT_INFORMATION";
export const CHANGE_EDUCATION = "CHANGE_EDUCATION";
export const CHANGE_EXPERIENCE = "CHANGE_EXPERIENCE";
export const CHANGE_SKILLS = "CHANGE_SKILLS";





